# Generated by Django 4.0.2 on 2022-04-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskslist',
            name='rand_tags',
            field=models.CharField(choices=[('New', 'New'), ('Running', 'Running'), ('Completed', 'Completed')], default='danger', max_length=15),
        ),
    ]
