# Generated by Django 4.0.2 on 2022-04-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_alter_taskslist_rand_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskslist',
            name='rand_tags',
            field=models.CharField(choices=[('New', 'New'), ('Running', 'Running'), ('Completed', 'Completed')], default='New', max_length=15),
        ),
    ]
